sudo: required
dist: trusty
language: node_js
node_js:
  - '7.4'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - export CHROME_BIN=/usr/bin/google-chrome
  
install:
- npm install -g ionic cordova
- npm install -g angular-cli
- npm install -g karma
- npm install -g protractor
- webdriver-manager update --standalone
- npm install

before_script:
- nohup bash -c "webdriver-manager start 2>&1"
- ionic serve --port=8100

script:
- protractor
- karma start karma.conf.js --single-run