sudo: required
dist: trusty
language: node_js
node_js:
  - '7.4'

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
- npm install -g ionic cordova
- npm install -g angular-cli
- npm install -g karma
- npm install -g protractor
- npm install -g webdriver-manager
- webdriver-manager update --standalone
- npm install
- nohup bash -c "webdriver-manager start 2>&1 &"

script:
- protractor
- karma start karma.conf.js --single-run